### ISSUE TITLE
Modelo Personas

### ISSUE THREAD

**Issue by ehx** [ehx/voluntAR#2]
Crear modelo para Personas

**Comment by andres2k** [comment]
Que version de Django usamos?

**Comment by ehx** [comment]
1.8 - 1.9 si queremos usar la ultima no hay problema

**Comment by andres2k** [comment]
- Cree el modelo Account que extiende de AbstractBaseUser para tener la funcionalidad de User y poder modificarlo para que tome como campo de identificacion y requerido el email
- Cree el modelo AccountManager que extiende de BaseUserManager para redefinir los metodos create_user y create_superuser.
- Cree el serializer y el viewset correspondiente.

Para hacer esto me base en un tutorial en internet donde explica como extender el User de django, para agregarle campos personalizados y otra funcionalidad.

**Comment by andres2k** [comment]
Falta: 
- Agregar login por usuario Facebook

**Comment by andres2k** [comment]
Queda para otro sprint (revisar) el incluir el login con el usuario de Facebook.
